CREATE DATABASE R61
ON
(
	NAME = 'R61_DATA_1',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\R61_DATA_1.mdf',
	SIZE=50MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10%
)
LOG ON 
(
	NAME = 'R61_LOG_1',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\R61_LOG_1.ldf',
	SIZE=50MB,
	MAXSIZE = 500MB,
	FILEGROWTH = 5%
)
GO
ALTER DATABASE R61
MODIFY FILE
(
	NAME = 'R61_LOG_1',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\R61_LOG_1.ldf',
	FILEGROWTH=10%
)
GO
ALTER DATABASE R61
ADD FILE
(
	NAME = 'R61_DATA_2',
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\R61_DATA_2.ndf',
	SIZE=20MB,
	MAXSIZE=100MB
)
GO
ALTER DATABASE R61
REMOVE FILE R61_DATA_2
GO
EXEC sp_helpdb 'R61'
GO
ALTER DATABASE R61
MODIFY NAME=R61A
GO
EXEC sp_renamedb R61A, R61
GO
DROP DATABASE R61
GO