RAISERROR('Fatal Error', 16, 1)
;
THROW 50001, 'Error', 16
BEGIN TRY
	INSERT INTO products VALUES (11, 'PP', 11)
END TRY
BEGIN CATCH
	DECLARE @msg NVARCHAR(500)= ERROR_MESSAGE()
	RAISERROR(@msg, 16, 1)
END CATCH
GO
