USE Northwind
GO
SELECT * FROM Customers
SELECT TOP 3 * FROM Customers
SELECT TOP 10 PERCENT * FROM Customers
GO
SELECT TOP 20 *
FROM Products
ORDER BY UnitPrice DESC
GO
SELECT TOP 15 WITH TIES *
FROM Products
ORDER BY UnitPrice DESC
GO
SELECT *
FROM Customers
ORDER BY CustomerID
OFFSET 10 ROWS
FETCH NEXT 10 ROWS ONLY
GO
SELECT * 
FROM Products
ORDER BY ProductID
OFFSET 20 ROWS
FETCH NEXT 10 ROWS ONLY