USE R61
GO
CREATE SEQUENCE seq1by1
AS INT
START WITH 1
INCREMENT BY 1
GO
CREATE TABLE idbclass
(
	id INT NOT NULL,
	topic NVARCHAR(40) NOT NULL
)
GO
INSERT INTO idbclass VALUES
(NEXT VALUE FOR seq1by1, 'CF 1'),
(NEXT VALUE FOR seq1by1, 'CF 2'),
(NEXT VALUE FOR seq1by1, 'CF 3')
GO
SELECT * FROM idbclass
GO

