// <auto-generated />
namespace R61M6C3wORKS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class rel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rel));
        
        string IMigrationMetadata.Id
        {
            get { return "202412040551598_rel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
