// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R61M9C12_HTTPCLIENT.Models;

#nullable disable

namespace R61M9C12_HTTPCLIENT.Migrations
{
    [DbContext(typeof(CourtDbContext))]
    partial class CourtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.CaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CurrentHearingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("NextHearingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CaseMasterId");

                    b.ToTable("CaseDetails");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.CaseMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("SectionId");

                    b.ToTable("CaseMasters");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtId"));

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourtId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.CaseDetail", b =>
                {
                    b.HasOne("R61M9C12_HTTPCLIENT.Models.CaseMaster", "CaseMaster")
                        .WithMany("CaseDetails")
                        .HasForeignKey("CaseMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseMaster");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.CaseMaster", b =>
                {
                    b.HasOne("R61M9C12_HTTPCLIENT.Models.Court", "Court")
                        .WithMany("Cases")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R61M9C12_HTTPCLIENT.Models.Section", "Section")
                        .WithMany("Cases")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.CaseMaster", b =>
                {
                    b.Navigation("CaseDetails");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.Court", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("R61M9C12_HTTPCLIENT.Models.Section", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
