// <auto-generated />
using System;
using CaseMasterDetails_APICore_consume.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseMasterDetails_APICore_consume.Migrations
{
    [DbContext(typeof(CaseContext))]
    [Migration("20250203062810_k1")]
    partial class k1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseMasterDetails_APICore_consume.Models.CaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CurrentHearingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("NextHearingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CaseMasterId");

                    b.ToTable("CaseDetails");
                });

            modelBuilder.Entity("CaseMasterDetails_APICore_consume.Models.CaseMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CaseMasters");
                });

            modelBuilder.Entity("CaseMasterDetails_APICore_consume.Models.CaseDetail", b =>
                {
                    b.HasOne("CaseMasterDetails_APICore_consume.Models.CaseMaster", "CaseMaster")
                        .WithMany("CaseDetails")
                        .HasForeignKey("CaseMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseMaster");
                });

            modelBuilder.Entity("CaseMasterDetails_APICore_consume.Models.CaseMaster", b =>
                {
                    b.Navigation("CaseDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
