// <auto-generated />
namespace R61M6C10_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class l : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(l));
        
        string IMigrationMetadata.Id
        {
            get { return "202412220430511_l"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
